apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uimmgxvzw-python
  janus-idp.io/tekton: uimmgxvzw-python
  backstage.io/kubernetes-id: uimmgxvzw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uimmgxvzw-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
